Feature/integrate mwss transformer
ONSdigital/sdx-ops pull request #1
Opened 2017-03-24 09:31 UTC by tundish

2017-03-27 10:09 UTC, JamesGardiner requested changes
A couple of questions here for you. One thing - can we add more error logging on exceptions where they aren't used for flow control?

2017-03-27 10:09 UTC, JamesGardiner commented on requirements.txt
>  cryptography>=1.5.3
This version of cryptography is out of sync with other services. I was under the impression that we want to keep this the same across services?=.

2017-03-27 10:09 UTC, JamesGardiner commented on sdx/common/async_consumer.py
> +logger = wrap_logger(logging.getLogger(__name__))
Define a formater for the logger first - `logging.basicConfig(level=LOGGING_LEVEL,
format=LOGGING_FORMAT)`

2017-03-27 10:09 UTC, JamesGardiner commented on sdx/common/async_consumer.py
> +logger = wrap_logger(logging.getLogger(__name__))
This will also initialise and add a streamhandler to stderr

2017-03-27 10:09 UTC, JamesGardiner commented on sdx/common/async_consumer.py
> +        logger.info('Channel opened')
Can the channel be logged?

2017-03-27 10:09 UTC, JamesGardiner commented on sdx/common/formats/cs_formatter.py
> +    def pck_name(survey_id, seq_nr, **kwargs):
Any reason for extra kwargs?

2017-03-29 10:39 UTC, tundish commented on sdx/common/formats/cs_formatter.py
> +    def pck_name(survey_id, seq_nr, **kwargs):
It's so you can call it like this:

```
ids = Survey.identifiers(reply)
name = CSFormatter.pck_name(**ids._asdict())
```

2017-03-29 10:46 UTC, JamesGardiner commented on sdx/common/formats/cs_formatter.py
> +    def pck_name(survey_id, seq_nr, **kwargs):
👍

2017-03-29 10:52 UTC, JamesGardiner approved these changes

2017-04-04 15:16 UTC, merged